# Generated by Django 2.2.5 on 2019-09-10 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('contato_id', models.AutoField(primary_key=True, serialize=False)),
                ('contato_nome', models.CharField(max_length=45)),
                ('contato_nascimento', models.DateField()),
                ('contato_sexo', models.CharField(choices=[('masculino', 'Masculino'), ('feminino', 'Feminino')], max_length=50)),
                ('contato_email', models.CharField(max_length=50)),
                ('contato_fone', models.CharField(max_length=11)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('em atendimento', 'Em Atendimento'), ('atendimento encerrado', 'Atendimento encerrado'), ('encerrado', 'Encerrado')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
